2015-02-10 14:42:09,632 /Users/djw/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-02-10 14:42:09,728 /Users/djw/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-02-10 14:42:09,773 /Users/djw/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-02-10 14:42:09,974 /Users/djw/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-02-10 14:42:10,043 /Users/djw/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-02-10 14:42:10,061 /Users/djw/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-02-10 14:42:10,061 /Users/djw/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-02-10 14:42:10,068 /Users/djw/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-02-10 14:42:10,069 /Users/djw/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 12:53:50,126 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 12:53:50,268 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 12:53:50,298 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 12:53:50,306 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 12:53:50,332 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 12:53:50,365 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 12:53:50,371 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 12:53:50,382 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 12:53:50,388 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 13:18:41,983 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 13:18:42,222 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 13:18:42,376 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 13:18:42,394 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 13:18:42,424 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 13:18:42,432 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 13:18:42,437 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 13:18:42,467 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 13:18:42,482 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 13:29:25,588 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 13:29:25,851 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 13:29:25,868 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 13:29:25,900 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 13:29:25,902 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 13:29:25,915 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 13:29:25,936 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 13:29:25,971 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 13:29:25,983 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 13:29:33,324 Exception on /processing.js [GET]
Traceback (most recent call last):
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/psiturk/experiment.py", line 664, in regularpage
    return render_template(pagename)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/djw/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/djw/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: processing.js
2015-03-03 13:29:33,700 Exception on /BANDIT03_PsiTurk.pde [GET]
Traceback (most recent call last):
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/psiturk/experiment.py", line 664, in regularpage
    return render_template(pagename)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/djw/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/djw/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: BANDIT03_PsiTurk.pde
2015-03-03 13:31:03,105 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 13:31:03,195 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 13:31:03,203 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 13:31:03,240 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 13:31:03,317 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 13:31:03,370 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 13:31:03,373 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 13:31:03,383 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 13:31:03,393 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 13:31:11,010 Exception on /processing.js [GET]
Traceback (most recent call last):
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/psiturk/experiment.py", line 664, in regularpage
    return render_template(pagename)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/djw/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/djw/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: processing.js
2015-03-03 13:31:11,249 Exception on /BANDIT03_PsiTurk.pde [GET]
Traceback (most recent call last):
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/psiturk/experiment.py", line 664, in regularpage
    return render_template(pagename)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/djw/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/djw/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: BANDIT03_PsiTurk.pde
2015-03-03 13:33:57,576 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 13:33:57,813 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 13:33:58,005 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 13:33:58,088 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 13:33:58,141 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 13:33:58,145 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 13:33:58,173 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 13:33:58,185 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 13:33:58,203 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 13:34:04,414 Exception on /processing.js [GET]
Traceback (most recent call last):
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/psiturk/experiment.py", line 664, in regularpage
    return render_template(pagename)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/djw/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/djw/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: processing.js
2015-03-03 13:34:04,576 Exception on /BANDIT03_PsiTurk.pde [GET]
Traceback (most recent call last):
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/psiturk/experiment.py", line 664, in regularpage
    return render_template(pagename)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/djw/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/djw/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: BANDIT03_PsiTurk.pde
2015-03-03 13:35:41,166 Exception on /BANDIT03_PsiTurk.pde [GET]
Traceback (most recent call last):
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/psiturk/experiment.py", line 664, in regularpage
    return render_template(pagename)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/djw/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/djw/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: BANDIT03_PsiTurk.pde
2015-03-03 13:36:02,356 Exception on /BANDIT03_PsiTurk.pde [GET]
Traceback (most recent call last):
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/psiturk/experiment.py", line 664, in regularpage
    return render_template(pagename)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/djw/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/djw/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: BANDIT03_PsiTurk.pde
2015-03-03 13:37:14,832 Exception on /BANDIT03_PsiTurk.pde [GET]
Traceback (most recent call last):
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/psiturk/experiment.py", line 664, in regularpage
    return render_template(pagename)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/djw/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/djw/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: BANDIT03_PsiTurk.pde
2015-03-03 13:37:28,589 Exception on /BANDIT03_PsiTurk.pde [GET]
Traceback (most recent call last):
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/psiturk/experiment.py", line 664, in regularpage
    return render_template(pagename)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/djw/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/djw/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: BANDIT03_PsiTurk.pde
2015-03-03 13:41:28,992 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 13:41:29,161 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 13:41:29,193 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 13:41:29,332 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 13:41:29,361 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 13:41:29,364 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 13:41:29,379 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 13:41:29,403 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 13:41:29,414 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 15:34:54,864 Exception on /Krungthep.ttf [GET]
Traceback (most recent call last):
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/psiturk/experiment.py", line 664, in regularpage
    return render_template(pagename)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/djw/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/djw/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: Krungthep.ttf
2015-03-03 15:35:09,099 Exception on /Krungthep.ttf [GET]
Traceback (most recent call last):
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/psiturk/experiment.py", line 664, in regularpage
    return render_template(pagename)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/djw/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/djw/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: Krungthep.ttf
2015-03-03 15:35:50,171 Exception on /Krungthep.ttf [GET]
Traceback (most recent call last):
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/psiturk/experiment.py", line 664, in regularpage
    return render_template(pagename)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/djw/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/djw/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: Krungthep.ttf
2015-03-03 16:55:59,610 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 16:55:59,848 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 16:55:59,863 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 16:55:59,878 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 16:55:59,884 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 16:55:59,885 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 16:55:59,925 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 16:55:59,927 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 16:55:59,937 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-03-03 17:46:17 -0500] [48601] [CRITICAL] WORKER TIMEOUT (pid:48608)
[2015-03-03 17:46:17 -0500] [48601] [CRITICAL] WORKER TIMEOUT (pid:48609)
[2015-03-03 17:46:17 -0500] [48601] [CRITICAL] WORKER TIMEOUT (pid:48610)
[2015-03-03 17:46:17 -0500] [48601] [CRITICAL] WORKER TIMEOUT (pid:48611)
[2015-03-03 17:46:17 -0500] [48601] [CRITICAL] WORKER TIMEOUT (pid:48612)
[2015-03-03 17:46:17 -0500] [48601] [CRITICAL] WORKER TIMEOUT (pid:48613)
[2015-03-03 17:46:17 -0500] [48601] [CRITICAL] WORKER TIMEOUT (pid:48605)
[2015-03-03 17:46:17 -0500] [48601] [CRITICAL] WORKER TIMEOUT (pid:48606)
[2015-03-03 17:46:17 -0500] [48601] [CRITICAL] WORKER TIMEOUT (pid:48607)
2015-03-03 17:46:20,405 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 17:46:20,405 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 17:46:20,411 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 17:46:20,423 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 17:46:20,439 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 17:46:20,449 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 17:46:20,456 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 17:46:20,456 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 17:46:20,474 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 22:09:46,929 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 22:09:46,940 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 22:09:47,038 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 22:09:47,107 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 22:09:47,246 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 22:09:47,278 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 22:09:47,297 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 22:09:47,327 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-03 22:09:47,341 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-03-04 00:20:00 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:50182)
[2015-03-04 00:20:00 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:50183)
[2015-03-04 00:20:00 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:50184)
[2015-03-04 00:20:00 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:50185)
[2015-03-04 00:20:00 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:50186)
[2015-03-04 00:20:00 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:50187)
[2015-03-04 00:20:00 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:50188)
[2015-03-04 00:20:00 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:50189)
[2015-03-04 00:20:00 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:50190)
2015-03-04 00:20:03,033 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 00:20:03,034 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 00:20:03,057 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 00:20:03,062 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 00:20:03,079 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 00:20:03,080 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 00:20:03,080 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 00:20:03,089 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 00:20:03,099 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-03-04 04:08:26 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:54144)
[2015-03-04 04:08:26 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:54145)
[2015-03-04 04:08:26 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:54146)
[2015-03-04 04:08:26 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:54147)
[2015-03-04 04:08:26 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:54148)
[2015-03-04 04:08:26 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:54140)
[2015-03-04 04:08:26 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:54141)
[2015-03-04 04:08:26 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:54142)
[2015-03-04 04:08:26 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:54143)
2015-03-04 04:08:28,208 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 04:08:28,185 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 04:08:28,210 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 04:08:28,212 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 04:08:28,219 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 04:08:28,226 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 04:08:28,226 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 04:08:28,229 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 04:08:28,249 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-03-04 09:25:56 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:55488)
[2015-03-04 09:25:56 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:55490)
[2015-03-04 09:25:56 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:55491)
[2015-03-04 09:25:56 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:55492)
[2015-03-04 09:25:56 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:55486)
[2015-03-04 09:25:56 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:55487)
2015-03-04 09:25:59,395 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 09:25:59,424 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 09:25:59,457 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 09:25:59,460 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 09:25:59,468 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 09:25:59,487 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-03-04 12:00:06 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:55489)
[2015-03-04 12:00:06 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:55498)
[2015-03-04 12:00:06 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:55499)
[2015-03-04 12:00:06 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:55500)
[2015-03-04 12:00:06 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:55501)
[2015-03-04 12:00:06 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:55502)
[2015-03-04 12:00:06 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:55503)
[2015-03-04 12:00:06 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:55484)
[2015-03-04 12:00:06 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:55485)
2015-03-04 12:00:08,176 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 12:00:08,198 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 12:00:08,208 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 12:00:08,223 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 12:00:08,225 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 12:00:08,253 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 12:00:08,284 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 12:00:08,303 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 12:00:08,315 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-03-04 13:26:08 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:58215)
[2015-03-04 13:26:08 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:58216)
[2015-03-04 13:26:08 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:58217)
[2015-03-04 13:26:08 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:58218)
[2015-03-04 13:26:08 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:58219)
[2015-03-04 13:26:08 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:58220)
[2015-03-04 13:26:08 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:58221)
[2015-03-04 13:26:08 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:58222)
[2015-03-04 13:26:08 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:58223)
2015-03-04 13:26:09,859 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 13:26:09,876 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 13:26:09,939 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 13:26:09,949 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 13:26:09,955 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 13:26:09,990 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 13:26:10,018 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 13:26:10,073 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 13:26:10,078 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-03-04 13:26:50 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:58230)
[2015-03-04 13:26:50 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:58231)
[2015-03-04 13:26:50 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:58232)
[2015-03-04 13:26:50 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:58233)
[2015-03-04 13:26:50 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:58234)
[2015-03-04 13:26:50 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:58235)
[2015-03-04 13:26:50 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:58236)
[2015-03-04 13:26:50 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:58237)
[2015-03-04 13:26:50 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:58238)
2015-03-04 13:26:51,582 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 13:26:51,586 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 13:26:51,586 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 13:26:51,612 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 13:26:51,623 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 13:26:51,660 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 13:26:51,721 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 13:26:51,752 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 13:26:51,763 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-03-04 16:34:49 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:58240)
[2015-03-04 16:34:49 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:58241)
[2015-03-04 16:34:49 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:58242)
[2015-03-04 16:34:49 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:58243)
[2015-03-04 16:34:49 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:58244)
[2015-03-04 16:34:49 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:58245)
[2015-03-04 16:34:49 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:58246)
[2015-03-04 16:34:49 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:58247)
[2015-03-04 16:34:49 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:58248)
2015-03-04 16:34:51,529 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 16:34:51,600 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 16:34:51,659 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 16:34:51,673 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 16:34:51,712 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 16:34:51,726 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 16:34:51,733 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 16:34:51,773 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 16:34:51,796 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-03-04 23:13:25 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:58262)
[2015-03-04 23:13:25 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:58263)
[2015-03-04 23:13:25 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:58264)
[2015-03-04 23:13:25 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:58265)
[2015-03-04 23:13:25 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:58270)
2015-03-04 23:13:30,679 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 23:13:30,680 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 23:13:30,699 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 23:13:30,713 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 23:13:30,729 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-03-04 23:22:21 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:58276)
[2015-03-04 23:22:21 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:58277)
[2015-03-04 23:22:21 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:58279)
[2015-03-04 23:22:21 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:58280)
[2015-03-04 23:22:21 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:58281)
[2015-03-04 23:22:21 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:58266)
[2015-03-04 23:22:21 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:58267)
[2015-03-04 23:22:21 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:58268)
[2015-03-04 23:22:21 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:58269)
2015-03-04 23:22:23,776 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 23:22:23,795 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 23:22:23,798 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 23:22:23,831 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 23:22:23,845 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 23:22:23,853 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 23:22:23,855 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 23:22:23,875 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 23:22:23,879 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-03-04 23:27:53 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:58709)
[2015-03-04 23:27:53 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:58710)
[2015-03-04 23:27:53 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:58711)
[2015-03-04 23:27:53 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:58712)
[2015-03-04 23:27:53 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:58713)
[2015-03-04 23:27:53 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:58714)
[2015-03-04 23:27:53 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:58715)
[2015-03-04 23:27:53 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:58716)
[2015-03-04 23:27:53 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:58717)
2015-03-04 23:27:55,979 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 23:27:55,981 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 23:27:55,982 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 23:27:56,050 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 23:27:56,065 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 23:27:56,107 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 23:27:56,114 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 23:27:56,124 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 23:27:56,126 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-03-04 23:54:54 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:58757)
[2015-03-04 23:54:54 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:58758)
[2015-03-04 23:54:54 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:58759)
[2015-03-04 23:54:54 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:58760)
[2015-03-04 23:54:54 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:58761)
[2015-03-04 23:54:54 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:58762)
[2015-03-04 23:54:54 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:58763)
[2015-03-04 23:54:54 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:58764)
[2015-03-04 23:54:54 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:58765)
2015-03-04 23:54:59,487 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 23:54:59,488 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 23:54:59,571 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 23:54:59,611 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 23:54:59,675 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 23:54:59,697 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 23:54:59,720 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 23:54:59,757 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-04 23:54:59,844 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-03-05 01:36:48 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:59282)
[2015-03-05 01:36:48 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:59283)
[2015-03-05 01:36:48 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:59284)
[2015-03-05 01:36:48 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:59285)
[2015-03-05 01:36:48 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:59286)
[2015-03-05 01:36:48 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:59287)
[2015-03-05 01:36:48 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:59288)
[2015-03-05 01:36:48 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:59289)
[2015-03-05 01:36:48 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:59290)
2015-03-05 01:36:50,700 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 01:36:50,713 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 01:36:50,726 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 01:36:50,736 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 01:36:50,748 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 01:36:50,749 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 01:36:50,805 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 01:36:50,808 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 01:36:50,816 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-03-05 02:35:19 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:59730)
[2015-03-05 02:35:19 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:59729)
[2015-03-05 02:35:19 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:59731)
[2015-03-05 02:35:19 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:59732)
[2015-03-05 02:35:19 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:59733)
[2015-03-05 02:35:19 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:59734)
[2015-03-05 02:35:19 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:59735)
[2015-03-05 02:35:19 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:59736)
[2015-03-05 02:35:19 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:59737)
2015-03-05 02:35:22,303 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 02:35:22,303 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 02:35:22,303 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 02:35:22,303 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 02:35:22,304 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 02:35:22,330 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 02:35:22,335 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 02:35:22,348 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 02:35:22,364 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-03-05 02:50:22 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:61123)
[2015-03-05 02:50:22 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:61124)
[2015-03-05 02:50:22 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:61125)
[2015-03-05 02:50:22 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:61126)
[2015-03-05 02:50:22 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:61128)
[2015-03-05 02:50:22 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:61129)
[2015-03-05 02:50:22 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:61130)
[2015-03-05 02:50:22 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:61131)
[2015-03-05 02:50:22 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:61132)
2015-03-05 02:50:24,592 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 02:50:24,595 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 02:50:24,606 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 02:50:24,618 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 02:50:24,618 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 02:50:24,623 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 02:50:24,624 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 02:50:24,689 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 02:50:24,717 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-03-05 05:55:12 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:61569)
[2015-03-05 05:55:12 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:61570)
[2015-03-05 05:55:12 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:61572)
[2015-03-05 05:55:12 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:61573)
[2015-03-05 05:55:12 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:61574)
[2015-03-05 05:55:12 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:61575)
[2015-03-05 05:55:12 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:61576)
[2015-03-05 05:55:12 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:61577)
[2015-03-05 05:55:12 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:61571)
2015-03-05 05:55:13,902 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 05:55:13,963 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 05:55:13,991 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 05:55:13,995 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 05:55:14,025 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 05:55:14,170 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 05:55:14,172 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 05:55:14,188 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 05:55:14,201 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-03-05 08:47:46 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:61984)
[2015-03-05 08:47:46 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:61985)
[2015-03-05 08:47:46 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:61979)
[2015-03-05 08:47:46 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:61980)
[2015-03-05 08:47:46 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:61981)
[2015-03-05 08:47:46 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:61982)
2015-03-05 08:47:49,547 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 08:47:49,560 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 08:47:49,569 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 08:47:49,569 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 08:47:49,570 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 08:47:49,570 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-03-05 11:49:31 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:61994)
[2015-03-05 11:49:31 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:61996)
[2015-03-05 11:49:31 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:61997)
[2015-03-05 11:49:31 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:61998)
[2015-03-05 11:49:31 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:61999)
[2015-03-05 11:49:31 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:62000)
[2015-03-05 11:49:31 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:61977)
[2015-03-05 11:49:31 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:61978)
[2015-03-05 11:49:31 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:61983)
2015-03-05 11:49:32,876 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 11:49:32,884 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 11:49:32,891 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 11:49:32,895 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 11:49:32,920 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 11:49:32,923 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 11:49:32,978 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 11:49:32,987 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 11:49:33,010 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-03-05 13:44:57 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:62051)
[2015-03-05 13:44:58 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:62052)
[2015-03-05 13:44:58 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:62053)
[2015-03-05 13:44:58 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:62054)
[2015-03-05 13:44:58 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:62055)
[2015-03-05 13:44:58 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:62056)
[2015-03-05 13:44:58 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:62057)
[2015-03-05 13:44:58 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:62058)
[2015-03-05 13:44:58 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:62059)
2015-03-05 13:45:03,082 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 13:45:03,145 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 13:45:03,201 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 13:45:03,205 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 13:45:03,209 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 13:45:03,211 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 13:45:03,211 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 13:45:03,222 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 13:45:03,239 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-03-05 17:13:05 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:62065)
[2015-03-05 17:13:05 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:62066)
[2015-03-05 17:13:05 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:62068)
[2015-03-05 17:13:05 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:62069)
[2015-03-05 17:13:05 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:62070)
[2015-03-05 17:13:05 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:62071)
[2015-03-05 17:13:05 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:62073)
[2015-03-05 17:13:05 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:62074)
[2015-03-05 17:13:05 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:62075)
2015-03-05 17:13:07,162 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 17:13:07,162 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 17:13:07,163 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 17:13:07,208 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 17:13:07,210 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 17:13:07,273 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 17:13:07,322 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 17:13:07,336 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-05 17:13:07,359 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-03-06 07:55:13 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:62912)
[2015-03-06 07:55:13 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:62913)
[2015-03-06 07:55:13 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:62914)
[2015-03-06 07:55:13 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:62917)
2015-03-06 07:55:18,840 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-06 07:55:18,883 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-06 07:55:18,887 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-06 07:55:18,894 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-03-06 11:47:18 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:62915)
[2015-03-06 11:47:18 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:62916)
[2015-03-06 11:47:18 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:62918)
[2015-03-06 11:47:18 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:62910)
[2015-03-06 11:47:18 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:62911)
2015-03-06 11:47:19,897 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-06 11:47:19,898 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-06 11:47:19,897 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-06 11:47:19,897 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-06 11:47:19,902 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-03-06 12:55:20 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:64308)
[2015-03-06 12:55:20 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:64309)
[2015-03-06 12:55:20 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:64311)
2015-03-06 12:55:26,448 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-06 12:55:26,449 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-06 12:55:26,451 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-03-06 16:47:24 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:64320)
[2015-03-06 16:47:24 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:62926)
[2015-03-06 16:47:24 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:62927)
[2015-03-06 16:47:24 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:62928)
[2015-03-06 16:47:24 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:62929)
[2015-03-06 16:47:24 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:64310)
[2015-03-06 16:47:24 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:64312)
2015-03-06 16:47:26,512 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-06 16:47:26,512 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-06 16:47:26,512 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-06 16:47:26,513 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-06 16:47:26,523 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-06 16:47:26,524 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-06 16:47:26,548 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-03-06 17:04:56 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:67585)
[2015-03-06 17:04:56 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:67586)
[2015-03-06 17:04:56 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:67587)
[2015-03-06 17:04:56 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:67588)
[2015-03-06 17:04:56 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:67589)
[2015-03-06 17:04:56 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:67590)
[2015-03-06 17:04:56 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:67591)
[2015-03-06 17:04:56 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:64318)
[2015-03-06 17:04:56 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:64319)
2015-03-06 17:04:57,790 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-06 17:04:57,811 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-06 17:04:57,814 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-06 17:04:57,826 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-06 17:04:57,828 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-06 17:04:57,831 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-06 17:04:57,842 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-06 17:04:57,916 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-06 17:04:57,933 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-03-06 17:39:30 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:67601)
[2015-03-06 17:39:30 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:67602)
[2015-03-06 17:39:30 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:67603)
[2015-03-06 17:39:30 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:67604)
[2015-03-06 17:39:30 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:67605)
[2015-03-06 17:39:30 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:67606)
[2015-03-06 17:39:30 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:67607)
[2015-03-06 17:39:30 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:67608)
[2015-03-06 17:39:30 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:67609)
2015-03-06 17:39:33,258 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-06 17:39:33,262 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-06 17:39:33,264 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-06 17:39:33,271 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-06 17:39:33,283 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-06 17:39:33,286 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-06 17:39:33,293 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-06 17:39:33,295 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-06 17:39:33,361 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-03-06 20:05:44 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:68480)
[2015-03-06 20:05:44 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:68471)
[2015-03-06 20:05:44 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:68472)
[2015-03-06 20:05:44 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:68473)
[2015-03-06 20:05:44 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:68474)
[2015-03-06 20:05:44 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:68476)
[2015-03-06 20:05:44 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:68477)
[2015-03-06 20:05:44 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:68478)
[2015-03-06 20:05:44 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:68479)
2015-03-06 20:05:45,700 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-06 20:05:45,725 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-06 20:05:45,744 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-06 20:05:45,790 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-06 20:05:45,799 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-06 20:05:45,813 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-06 20:05:45,853 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-03-06 21:48:33 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:72457)
[2015-03-06 21:48:33 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:72458)
[2015-03-06 21:48:33 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:72459)
[2015-03-06 21:48:33 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:72460)
[2015-03-06 21:48:33 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:72461)
[2015-03-06 21:48:33 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:72462)
[2015-03-06 21:48:33 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:72463)
[2015-03-06 21:48:33 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:72464)
[2015-03-06 21:48:33 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:72465)
2015-03-06 21:48:34,964 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-06 21:48:34,964 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-06 21:48:34,965 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-06 21:48:35,000 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-06 21:48:35,025 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-06 21:48:35,087 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-06 21:48:35,129 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-06 21:48:35,137 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-06 21:48:35,173 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-03-06 22:33:45 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:72467)
[2015-03-06 22:33:45 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:72468)
[2015-03-06 22:33:45 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:72469)
[2015-03-06 22:33:45 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:72470)
[2015-03-06 22:33:45 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:72471)
[2015-03-06 22:33:45 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:72472)
[2015-03-06 22:33:45 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:72473)
[2015-03-06 22:33:45 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:72474)
[2015-03-06 22:33:45 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:72475)
2015-03-06 22:33:47,855 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-06 22:33:47,856 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-06 22:33:47,871 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-06 22:33:47,875 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-06 22:33:47,889 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-06 22:33:47,891 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-06 22:33:47,927 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-06 22:33:47,938 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-06 22:33:47,949 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-03-07 02:42:18 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:73344)
[2015-03-07 02:42:18 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:73336)
[2015-03-07 02:42:18 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:73337)
[2015-03-07 02:42:18 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:73338)
[2015-03-07 02:42:18 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:73339)
[2015-03-07 02:42:18 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:73340)
[2015-03-07 02:42:18 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:73341)
[2015-03-07 02:42:18 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:73342)
[2015-03-07 02:42:18 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:73343)
2015-03-07 02:42:20,574 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-07 02:42:20,575 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-07 02:42:20,575 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-07 02:42:20,587 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-07 02:42:20,597 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-07 02:42:20,605 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-07 02:42:20,613 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-07 02:42:20,617 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-07 02:42:20,625 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-03-07 08:19:12 -0500] [50178] [CRITICAL] WORKER TIMEOUT (pid:75027)
2015-03-07 08:19:17,311 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-07 08:25:29,812 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-07 08:25:29,884 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-07 08:25:29,958 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-07 08:25:30,047 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-07 08:25:30,103 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-07 08:25:30,186 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-07 08:25:30,193 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-07 08:25:30,194 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-07 08:25:30,205 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-07 09:28:01,337 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-07 09:28:01,520 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-07 09:28:01,541 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-07 09:28:01,706 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-07 09:28:01,722 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-07 09:28:01,758 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-07 09:28:01,799 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-07 09:28:01,828 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-07 09:28:01,864 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-10 14:02:34,808 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-10 14:02:34,917 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-10 14:02:35,135 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-10 14:02:35,187 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-10 14:02:35,251 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-10 14:02:35,252 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-10 14:02:35,274 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-10 14:02:35,278 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-10 14:02:35,280 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-10 14:16:02,356 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-10 14:16:02,441 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-10 14:16:02,449 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-10 14:16:02,468 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-10 14:16:02,535 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-10 14:16:02,617 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-10 14:16:02,627 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-10 14:16:02,638 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-10 14:16:02,650 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-10 14:18:58,411 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-10 14:18:58,433 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-10 14:18:58,615 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-10 14:18:58,688 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-10 14:18:58,803 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-10 14:18:58,806 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-10 14:18:58,933 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-10 14:18:58,954 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-10 14:18:59,004 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-10 16:10:32,552 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-10 16:10:32,555 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-10 16:10:32,729 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-10 16:10:32,928 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-10 16:10:32,938 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-10 16:10:32,971 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-10 16:10:32,973 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-10 16:10:32,978 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-10 16:10:32,981 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-10 16:14:23,350 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-10 16:14:23,533 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-10 16:14:23,614 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-10 16:14:23,687 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-10 16:14:23,732 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-10 16:14:23,735 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-10 16:14:23,764 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-10 16:14:23,775 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-10 16:14:23,785 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-10 16:47:06,806 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-10 16:47:07,083 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-10 16:47:07,374 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-10 16:47:07,455 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-10 16:47:07,523 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-10 16:47:07,566 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-10 16:47:07,593 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-10 16:47:07,597 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-03-10 16:47:07,608 /Users/djw/anaconda/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-03-10 17:59:47 -0400] [8161] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/arbiter.py", line 503, in spawn_worker
    worker.init_process()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/workers/base.py", line 116, in init_process
    self.wsgi = self.app.wsgi()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/Users/djw/GitHub/Bandit-mechanicalTurk/psiturk-bandit/custom.py", line 90
    bonus = trial['payout']
    ^
IndentationError: unexpected indent
Traceback (most recent call last):
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/arbiter.py", line 503, in spawn_worker
    worker.init_process()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/workers/base.py", line 116, in init_process
    self.wsgi = self.app.wsgi()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/Users/djw/GitHub/Bandit-mechanicalTurk/psiturk-bandit/custom.py", line 90
    bonus = trial['payout']
    ^
IndentationError: unexpected indent
[2015-03-10 17:59:47 -0400] [8159] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/arbiter.py", line 503, in spawn_worker
    worker.init_process()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/workers/base.py", line 116, in init_process
    self.wsgi = self.app.wsgi()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/Users/djw/GitHub/Bandit-mechanicalTurk/psiturk-bandit/custom.py", line 90
    bonus = trial['payout']
    ^
IndentationError: unexpected indent
Traceback (most recent call last):
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/arbiter.py", line 503, in spawn_worker
    worker.init_process()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/workers/base.py", line 116, in init_process
    self.wsgi = self.app.wsgi()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/Users/djw/GitHub/Bandit-mechanicalTurk/psiturk-bandit/custom.py", line 90
    bonus = trial['payout']
    ^
IndentationError: unexpected indent
[2015-03-10 17:59:47 -0400] [8165] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/arbiter.py", line 503, in spawn_worker
    worker.init_process()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/workers/base.py", line 116, in init_process
    self.wsgi = self.app.wsgi()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/Users/djw/GitHub/Bandit-mechanicalTurk/psiturk-bandit/custom.py", line 90
    bonus = trial['payout']
    ^
IndentationError: unexpected indent
Traceback (most recent call last):
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/arbiter.py", line 503, in spawn_worker
    worker.init_process()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/workers/base.py", line 116, in init_process
    self.wsgi = self.app.wsgi()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/Users/djw/GitHub/Bandit-mechanicalTurk/psiturk-bandit/custom.py", line 90
    bonus = trial['payout']
    ^
IndentationError: unexpected indent
[2015-03-10 17:59:47 -0400] [8158] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/arbiter.py", line 503, in spawn_worker
    worker.init_process()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/workers/base.py", line 116, in init_process
    self.wsgi = self.app.wsgi()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/Users/djw/GitHub/Bandit-mechanicalTurk/psiturk-bandit/custom.py", line 90
    bonus = trial['payout']
    ^
IndentationError: unexpected indent
Traceback (most recent call last):
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/arbiter.py", line 503, in spawn_worker
    worker.init_process()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/workers/base.py", line 116, in init_process
    self.wsgi = self.app.wsgi()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/Users/djw/GitHub/Bandit-mechanicalTurk/psiturk-bandit/custom.py", line 90
    bonus = trial['payout']
    ^
IndentationError: unexpected indent
[2015-03-10 17:59:47 -0400] [8163] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/arbiter.py", line 503, in spawn_worker
    worker.init_process()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/workers/base.py", line 116, in init_process
    self.wsgi = self.app.wsgi()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/Users/djw/GitHub/Bandit-mechanicalTurk/psiturk-bandit/custom.py", line 90
    bonus = trial['payout']
    ^
IndentationError: unexpected indent
Traceback (most recent call last):
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/arbiter.py", line 503, in spawn_worker
    worker.init_process()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/workers/base.py", line 116, in init_process
    self.wsgi = self.app.wsgi()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/Users/djw/GitHub/Bandit-mechanicalTurk/psiturk-bandit/custom.py", line 90
    bonus = trial['payout']
    ^
IndentationError: unexpected indent
[2015-03-10 17:59:47 -0400] [8164] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/arbiter.py", line 503, in spawn_worker
    worker.init_process()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/workers/base.py", line 116, in init_process
    self.wsgi = self.app.wsgi()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/Users/djw/GitHub/Bandit-mechanicalTurk/psiturk-bandit/custom.py", line 90
    bonus = trial['payout']
    ^
IndentationError: unexpected indent
Traceback (most recent call last):
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/arbiter.py", line 503, in spawn_worker
    worker.init_process()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/workers/base.py", line 116, in init_process
    self.wsgi = self.app.wsgi()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/Users/djw/GitHub/Bandit-mechanicalTurk/psiturk-bandit/custom.py", line 90
    bonus = trial['payout']
    ^
IndentationError: unexpected indent
[2015-03-10 17:59:47 -0400] [8160] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/arbiter.py", line 503, in spawn_worker
    worker.init_process()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/workers/base.py", line 116, in init_process
    self.wsgi = self.app.wsgi()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/Users/djw/GitHub/Bandit-mechanicalTurk/psiturk-bandit/custom.py", line 90
    bonus = trial['payout']
    ^
IndentationError: unexpected indent
Traceback (most recent call last):
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/arbiter.py", line 503, in spawn_worker
    worker.init_process()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/workers/base.py", line 116, in init_process
    self.wsgi = self.app.wsgi()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/Users/djw/GitHub/Bandit-mechanicalTurk/psiturk-bandit/custom.py", line 90
    bonus = trial['payout']
    ^
IndentationError: unexpected indent
[2015-03-10 17:59:47 -0400] [8162] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/arbiter.py", line 503, in spawn_worker
    worker.init_process()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/workers/base.py", line 116, in init_process
    self.wsgi = self.app.wsgi()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/Users/djw/GitHub/Bandit-mechanicalTurk/psiturk-bandit/custom.py", line 90
    bonus = trial['payout']
    ^
IndentationError: unexpected indent
Traceback (most recent call last):
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/arbiter.py", line 503, in spawn_worker
    worker.init_process()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/workers/base.py", line 116, in init_process
    self.wsgi = self.app.wsgi()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/Users/djw/GitHub/Bandit-mechanicalTurk/psiturk-bandit/custom.py", line 90
    bonus = trial['payout']
    ^
IndentationError: unexpected indent
[2015-03-10 17:59:47 -0400] [8166] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/arbiter.py", line 503, in spawn_worker
    worker.init_process()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/workers/base.py", line 116, in init_process
    self.wsgi = self.app.wsgi()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/Users/djw/GitHub/Bandit-mechanicalTurk/psiturk-bandit/custom.py", line 90
    bonus = trial['payout']
    ^
IndentationError: unexpected indent
Traceback (most recent call last):
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/arbiter.py", line 503, in spawn_worker
    worker.init_process()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/workers/base.py", line 116, in init_process
    self.wsgi = self.app.wsgi()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/djw/anaconda/lib/python2.7/site-packages/psiturk/experiment_server.py", line 49, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/djw/anaconda/lib/python2.7/site-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/Users/djw/anaconda/lib/python2.7/site-packages/psiturk/experiment.py", line 71, in <module>
    from custom import custom_code
  File "/Users/djw/GitHub/Bandit-mechanicalTurk/psiturk-bandit/custom.py", line 90
    bonus = trial['payout']
    ^
IndentationError: unexpected indent
